### ISSUE TITLE
Python - Not all headings are found

### ISSUE THREAD

**Issue by tim-hilde** [chrisgrieser/alfred-docs-searches#1]
### Bug Description

When searching the python docs I'd would expect that I can find every heading. But this is not the case e.g. [Built-in Types](https://docs.python.org/3.11/library/stdtypes.html) are not found via the workflow

### Debugging Log

[log.txt](https://github.com/chrisgrieser/alfred-docs-searches/files/12093076/log.txt)

### Workflow Configuration

<img width="1212" alt="image" src="https://github.com/chrisgrieser/alfred-docs-searches/assets/44113468/df4c0633-0482-472a-98ea-724384c0b590">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-docs-searches/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Well, the current implementation of the Python Docs Search only looks for titles of pages, in your case "stdtypes". It's not ideal for sure, but technically not a bug, but rather a FR 😅 

Implementing searching of headings in the python docs would take quite a bit of extra effort. If anyone wants to give it a try, [it's this file you'd have to work with](https://github.com/chrisgrieser/alfred-docs-searches/blob/main/scripts/python-docs.js).

**Comment by chrisgrieser** [comment]
Okay, I figured out a way to correctly fetch all headings in the python docs. Added in the latest release 1.14.1

https://github.com/chrisgrieser/alfred-docs-searches/releases/download/1.14.1/alfred-docs-searches.alfredworkflow
