### ISSUE TITLE
Keywords for devdocs searches don't work (py, js, c, r, etc)

### ISSUE THREAD

**Issue by Azrael2312** [chrisgrieser/alfred-docs-searches#10]
For some reason only extra documentation (biome, ruff, etc) works,  but documentation from DevDocs don't. I tried reinstalling, and the issue still persists. I hope you can help me.

**Comment by chrisgrieser** [comment]
I assume you found what was causing the issue on your end?

**Comment by Azrael2312** [comment]
Yep, sorry for bother you. I forgot to turn on Automation 😅️
