### ISSUE TITLE
Feature Request: PHP & Tailwind CSS docs

### ISSUE THREAD

**Issue by alexbet** [chrisgrieser/alfred-docs-searches#2]
### Feature Requested

Can you please add PHP, Tailwind CSS, and Vue.js docs? Thank you!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi, since I do not use those languages myself, I cannot add them myself, but PRs adding searches for them as welcome.

Adding a new language is fairly straightforward, for most cases, the searches are 10-20 lines of code: https://github.com/chrisgrieser/alfred-docs-searches/tree/main/scripts

**Comment by chrisgrieser** [comment]
With version 2.0, this workflow has been overhauled to include all devdocs, meaning Tailwind and PHP are now supported.

https://github.com/chrisgrieser/alfred-docs-searches/releases/download/2.0.0/alfred-docs-searches.alfredworkflow
