### ISSUE TITLE
[Bug]: Pandas not documented

### ISSUE THREAD

**Issue by vitorgalvao** [chrisgrieser/alfred-docs-searches#3]
### Bug Description

Pandas documentation was added in `1.8.0`, but it was not added to the GitHub README or the workflow’s About.

### Relevant Screenshot

Not applicable. Issue is about missing documentation.

### To Reproduce

Not applicable. Issue is about missing documentation.

### Debugging Log

```Text
Not applicable. Issue is about missing documentation.
```

### Workflow Configuration

Not applicable. Issue is about missing documentation.

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-docs-searches/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Oh thanks, forgot. Fixed. Should probably add some tests and/or automation, for
this workflow. 🙈

You really are vigilant with my workflow updates. 😅

**Comment by vitorgalvao** [comment]
Everyone’s updates, really. Keeping the Gallery running smooth!
