### ISSUE TITLE
Request Docs Site: NextJS

### ISSUE THREAD

**Issue by okilonet1** [chrisgrieser/alfred-docs-searches#5]
### Documentation Site Requested

https://nextjs.org/docs

### Checklist

- [X] The site is considered an authoritative source of information in the area.

**Comment by chrisgrieser** [comment]
Hi,

This workflow already supports dozens of documentation sites, and I possibly maintain even more, I have to decline requests to add additional sites. However, I am open to contributions adding more sites, it requires less than 50 lines of code to add a site. See the information here on how to contribute: https://github.com/chrisgrieser/alfred-docs-searches?tab=readme-ov-file#contribute
