### ISSUE TITLE
[Feature] Building it with devdoc

### ISSUE THREAD

**Issue by AjayShanker-geek** [chrisgrieser/alfred-docs-searches#6]
### Bug Description

Hi, I wrote a post in Alfred forum to use devdoc and the markdown preview as an idea. [Here](https://www.alfredforum.com/topic/21746-devdoc-with-markdown-view/)

### Debugging Log

```Text
nil
```

### Workflow Configuration

nil

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-docs-searches/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Huh, interesting. I once looked into devdocs, but didn't find any documentation on how to get their index.  `https://documents.devdocs.io/lang/index.json` appears to be quite interesting. How did you find that one? Also any idea if there is a list of all available languages somewhere?

**Comment by AjayShanker-geek** [comment]
[nvim-devdoc](https://github.com/luckasRanarison/nvim-devdocs) is the project I read.

**Comment by chrisgrieser** [comment]
I see. Huh, those indexes are undocumented, but if nvim-devdocs is using them, I guess they are good enough to use. List of languages/docs seems to be here: https://devdocs.io/docs.json

I'll see what I can do, does look pretty straightforward to implement.

**Comment by chrisgrieser** [comment]
Okay, I have completely rewritten the workflow to now use devdocs 😅 

https://github.com/chrisgrieser/alfred-docs-searches/releases/download/2.0.0/alfred-docs-searches.alfredworkflow

**Comment by AjayShanker-geek** [comment]
Cool! That was fast

**Comment by chrisgrieser** [comment]
Had an empty Sunday for once 😅

**Comment by AjayShanker-geek** [comment]
Haha, I will look into if I am able to dump and convert in markdown. Hopefully I can use it markdown preview within Alfred
